---
- name: Install Onlyoffice Docker Compose on AlmaLinux/RHEL
  hosts: alma
  become: true
  gather_facts: true
  vars_files:
    - onlyvault.yml
  vars:
    docker_user: "{{ ansible_user | default(default_user) }}"
    onlyoffice_data_path: "{{ install_path }}"
    postgres_password: "{{ db_password }}"
    jwt_secret: "{{ onlyoffice_jwt_secret }}"

  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install required packages
      dnf:
        name:
          - nano
          - wget
          - git
          - unzip
          - qemu-guest-agent
        state: present

    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Test Docker installation
      command: docker run hello-world
      register: test_output
      changed_when: false

    - name: Display test output
      debug:
        var: test_output.stdout_lines

    - name: Install OpenSSL and Python dependencies
      dnf:
        name:
          - openssl
          - python3-pip
          - python3-devel
          - gcc
          - openssl-devel
        state: present

    - name: Install Python cryptography package
      pip:
        name: cryptography>=1.2.3
        state: present

    - name: Create ONLYOFFICE directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: '{{ onlyoffice_data_path }}', mode: '0755' }
        - { path: '{{ onlyoffice_data_path }}/logs', mode: '0755' }
        - { path: '{{ onlyoffice_data_path }}/data', mode: '0755' }
        - { path: '{{ onlyoffice_data_path }}/lib', mode: '0755' }
        - { path: '{{ onlyoffice_data_path }}/db', mode: '0755' }
        - { path: '{{ onlyoffice_data_path }}/certs', mode: '0755' }

    - name: Generate SSL private key
      openssl_privatekey:
        path: "{{ onlyoffice_data_path }}/certs/onlyoffice.key"
        size: 2048
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0600'

    - name: Generate SSL CSR
      openssl_csr:
        path: "{{ onlyoffice_data_path }}/certs/onlyoffice.csr"
        privatekey_path: "{{ onlyoffice_data_path }}/certs/onlyoffice.key"
        common_name: "{{ internal_domain }}"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0600'

    - name: Generate self-signed SSL certificate
      openssl_certificate:
        path: "{{ onlyoffice_data_path }}/certs/onlyoffice.crt"
        privatekey_path: "{{ onlyoffice_data_path }}/certs/onlyoffice.key"
        csr_path: "{{ onlyoffice_data_path }}/certs/onlyoffice.csr"
        provider: selfsigned
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0644'

    - name: Generate DHparam file
      command: openssl dhparam -out {{ onlyoffice_data_path }}/certs/dhparam.pem 2048
      args:
        creates: "{{ onlyoffice_data_path }}/certs/dhparam.pem"

    - name: Create compose.yaml for ONLYOFFICE
      copy:
        dest: "{{ onlyoffice_data_path }}/compose.yaml"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0644'
        content: |
          version: '3.8'
          services:
            onlyoffice-documentserver:
              image: onlyoffice/documentserver:latest
              container_name: onlyoffice
              restart: always
              ports:
                - "443:443"
                - "80:80"
              extra_hosts:
                - "{{ internal_domain }}:127.0.0.1"
              environment:
                - JWT_ENABLED=true
                - JWT_SECRET={{ jwt_secret }}
                - JWT_HEADER=Authorization
                - JWT_IN_BODY=true
                - JWT_ACCEPT_UNSIGNED=true
                - JWT_REFUSE_UNAUTHORIZED=false
                - TRENDS_ENABLED=false
                - USE_UNAUTHORIZED_STORAGE=true
                - ALLOWED_HOSTS=*
                - VERIFY_PEER_OFF=true
                - NODE_TLS_REJECT_UNAUTHORIZED=0
                - CHECK_IP=false
                - NGINX_DISABLE_SECURECOOKIE=true
                # Document server connection settings for internal network
                - DOCUMENT_SERVER_HOST=https://192.168.100.46
                - DOCUMENT_SERVER_PORT_80_TCP_ADDR=192.168.100.46
                - DOCUMENT_SERVER_PORT_80_TCP_PORT=443
                - DOCUMENT_SERVER_PROTOCOL=https
                # Security and access settings for internal network
                - TRUSTED_DOMAINS=192.168.100.*
                - DOC_SERV_SITE_URL=https://192.168.100.46
                - WOPI_ALLOWED_HOSTS=*
                - DOC_SERV_CORS_ALLOWED_ORIGINS=https://192.168.100.*
                - ALLOW_PRIVATE_IP_ADDRESS=true
                # Security settings for internal usage
                - JWT_ENABLED=true
                - JWT_ACCEPT_UNSIGNED=false
                - JWT_REJECT_UNAUTHORIZED=false
                - VERIFY_PEER_OFF=true
                - CHECK_IP=false
                - ALLOW_INTERNAL_CONNECTIONS=true
                # Performance settings for multiple instances
                - FILE_UPLOAD_MAX_MEMORY=1000000000
                - METRICS_ENABLED=true
                - MAX_CONVERTER_PROCESSES=10
                - APP_METRICS_ENABLED=true
                - PUPPETEER_CHROMIUM_REVISION=982053
                - MAX_CONNECTIONS=100
                - DB_TYPE=postgres
                - DB_HOST=onlyoffice-postgresql
                - DB_PORT=5432
                - DB_NAME=onlyoffice
                - DB_USER=onlyoffice
                - DB_PWD={{ postgres_password }}
                - VIRTUAL_HOST={{ internal_domain }}
                - WOPI_ALLOWED_HOSTS=*
                # HTTPS Configuration
                - HTTPS_TRUE=true
                - SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/onlyoffice.crt
                - SSL_KEY_PATH=/var/www/onlyoffice/Data/certs/onlyoffice.key
                - SSL_DHPARAM_PATH=/var/www/onlyoffice/Data/certs/dhparam.pem
                # Additional security settings
                - ALLOW_CORS_HEADERS=true
                - USE_UNAUTHORIZED_STORAGE=true
                # Conversion settings
                - FILE_UPLOAD_ENABLE_BLANK_DETERMINATION=true
                - FILE_UPLOAD_SIZE_MAX=102400
                - FILE_UPLOAD_TIMEOUT=60
                - MAX_CONVERTER_PROCESSES=5
                - GENERATE_FONTS=true
              user: "root"
              healthcheck:
                test: ["CMD", "curl", "-f", "https://localhost/healthcheck"]
                interval: 30s
                timeout: 10s
                retries: 3
              volumes:
                - ./logs:/var/log/onlyoffice:rw
                - ./data:/var/www/onlyoffice/Data:rw
                - ./lib:/var/lib/onlyoffice:rw
                - ./certs:/var/www/onlyoffice/Data/certs:rw

            onlyoffice-postgresql:
              image: postgres:13
              container_name: onlyoffice-postgresql
              restart: always
              ports:
                - "5432:5432"
              environment:
                - POSTGRES_DB=onlyoffice
                - POSTGRES_USER=onlyoffice
                - POSTGRES_PASSWORD={{ postgres_password }}
              volumes:
                - ./db:/var/lib/postgresql/data

    - name: Create configuration guide
      copy:
        dest: "{{ onlyoffice_data_path }}/README.md"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0644'
        content: |
          # ONLYOFFICE Document Server Configuration Guide

          ## Internal Access Only Setup

          This ONLYOFFICE Document Server is configured for secure HTTPS access.
          Server address: https://{{ internal_domain }}

          ## SSL Certificate Information
          Self-signed SSL certificates are automatically generated during installation:
          - A SSL certificate and private key for secure HTTPS access
          - DHparam file for enhanced SSL security
          
          Note: These are self-signed certificates suitable for testing and internal use.
          For production use, consider replacing them with certificates from a trusted Certificate Authority.

          ## Multi-Instance Nextcloud Integration (Internal Network)

          This ONLYOFFICE Document Server is configured to work with multiple Nextcloud instances
          over the internal network (192.168.100.0/24).

          For each Nextcloud instance:

          1. Install the ONLYOFFICE connector app:
             - Go to Apps > Office & Text
             - Find and install "ONLYOFFICE"

          2. Configure the ONLYOFFICE app in each Nextcloud instance:
             - Go to Settings > ONLYOFFICE
             - Document Editing Service address: https://192.168.100.46
             - Secret key: {{ jwt_secret }}
             - Enable "Advanced server settings"
             - Check "Enable advanced server connection settings"
             - Enable JWT Secret (required for security)
             - Uncheck "Verify SSL certificate" (since we're using self-signed certificate)

          3. Important: Certificate Setup
             - Since we're using a self-signed certificate, you need to add it as trusted
             - On each Nextcloud server, run:
               ```bash
               sudo cp {{ onlyoffice_data_path }}/certs/onlyoffice.crt /usr/local/share/ca-certificates/
               sudo update-ca-certificates
               ```
             - Restart your Nextcloud container after adding the certificate

          3. Add trusted domains in each Nextcloud instance:
             - Go to Settings > Administration > General
             - Under "Trusted Domains", add: {{ internal_domain }}

          4. Performance Recommendations:
             - For better performance, configure each Nextcloud instance to use Redis
             - Consider using a load balancer if connecting more than 10 instances
             - Monitor server resources and adjust MAX_CONVERTER_PROCESSES if needed

          ## Security Notes

          - Server is configured for internal LAN access only
          - JWT authentication is enabled for secure communication
          - Each Nextcloud instance must use the same JWT secret
          - All data is stored locally in the onlyoffice directory

          ## File Locations

          All data is stored in /home/{{ docker_user }}/onlyoffice:
          - ./logs: Server logs
          - ./data: Document data
          - ./lib: Library files
          - ./db: PostgreSQL database
          - ./certs: SSL certificates (if needed)
          - compose.yaml: Docker compose configuration

          ## Testing the Installation

          Visit https://{{ internal_domain }}/healthcheck
          You should see a JSON response indicating the service status.

    - name: Set proper permissions on ONLYOFFICE directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0755"
      with_items:
        - "{{ onlyoffice_data_path }}/logs"
        - "{{ onlyoffice_data_path }}/data"
        - "{{ onlyoffice_data_path }}/lib"
        - "{{ onlyoffice_data_path }}/db"

    - name: Create data certs directory
      file:
        path: "{{ onlyoffice_data_path }}/data/certs"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0755"

    - name: Copy certificates to data directory
      copy:
        src: "{{ onlyoffice_data_path }}/certs/{{ item }}"
        dest: "{{ onlyoffice_data_path }}/data/certs/{{ item }}"
        remote_src: yes
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"
      with_items:
        - onlyoffice.crt
        - onlyoffice.key
        - dhparam.pem

    - name: Start ONLYOFFICE containers
      command: docker compose up -d
      args:
        chdir: "{{ onlyoffice_data_path }}"

    - name: Wait for services to start
      pause:
        seconds: 30

    - name: Check ONLYOFFICE logs
      command: docker logs onlyoffice
      register: onlyoffice_logs
      ignore_errors: yes

    - name: Display ONLYOFFICE logs
      debug:
        var: onlyoffice_logs.stdout_lines

    - name: Verify ONLYOFFICE is accessible
      uri:
        url: "https://{{ internal_domain }}/healthcheck"
        validate_certs: no
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 6
      delay: 10
      ignore_errors: yes

    - name: Display health check result
      debug:
        var: health_check

    - name: Create public directory for certificate sharing
      file:
        path: "{{ onlyoffice_data_path }}/public"
        state: directory
        mode: '0755'
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"

    - name: Copy certificate to public directory
      copy:
        src: "{{ onlyoffice_data_path }}/certs/onlyoffice.crt"
        dest: "{{ onlyoffice_data_path }}/public/onlyoffice.crt"
        mode: '0644'
        remote_src: yes
