---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_os_family == "Ubuntu"

- hosts: docker1
  become: true
  tasks:
    - name: Install Cockpit and related packages (Ubuntu)
      apt:
        name:
          - cockpit
          - cockpit-navigator
          - cockpit-dockermanager
        state: latest
      when: ansible_os_family