---
- name: Install Docker on AlmaLinux/RHEL
  hosts: alma
  become: true
  gather_facts: true
  vars_files:
    - vault.yml
  vars:
    docker_user: "{{ ansible_user | default('sasho') }}"
    nextcloud_data_path: "/home/{{ docker_user }}/cloud"
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install required packages
      dnf:
        name:
          - nano
          - wget
          - git
          - unzip
          - qemu-guest-agent
        state: present

    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Test Docker installation
      command: docker run hello-world
      register: test_output
      changed_when: false

    - name: Display test output
      debug:
        var: test_output.stdout_lines

    - name: Set up Nextcloud directory structure with proper permissions
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: '{{ nextcloud_data_path }}', owner: '{{ docker_user }}', group: '{{ docker_user }}', mode: '0775' }
        - { path: '{{ nextcloud_data_path }}/config', owner: '33', group: '33', mode: '0775' }
        - { path: '{{ nextcloud_data_path }}/custom_apps', owner: '33', group: '33', mode: '0775' }
        - { path: '{{ nextcloud_data_path }}/data', owner: '33', group: '33', mode: '0770' }
        - { path: '{{ nextcloud_data_path }}/db', owner: '999', group: '{{ docker_user }}', mode: '0700' }
        - { path: '{{ nextcloud_data_path }}/logs', owner: '33', group: '33', mode: '0775' }
        - { path: '{{ nextcloud_data_path }}/themes', owner: '33', group: '33', mode: '0775' }

    - name: Create apache.conf file
      copy:
        dest: "{{ nextcloud_data_path }}/apache.conf"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0664'
        content: |
          ServerName {{ domain_name }}

          <VirtualHost *:80>
              ServerName {{ domain_name }}
              DocumentRoot /var/www/html

              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
        mode: '0664'
        owner: sasho
        group: sasho

    - name: Create docker-compose.yaml for Nextcloud
      copy:
        dest: "{{ nextcloud_data_path }}/compose.yaml"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0664'
        content: |
          services:
            nextcloud:
              image: nextcloud:latest
              container_name: cloud
              restart: always
              ports:
                - "80:80"
                - "443:443"
              depends_on:
                - db
                - redis
              volumes:
                - {{ nextcloud_data_path }}/data:/var/www/html/data
                - {{ nextcloud_data_path }}/config:/var/www/html/config
                - {{ nextcloud_data_path }}/custom_apps:/var/www/html/custom_apps
                - {{ nextcloud_data_path }}/themes:/var/www/html/themes
                - {{ nextcloud_data_path }}/logs:/var/www/html/data/logs
                - {{ nextcloud_data_path }}/apache.conf:/etc/apache2/sites-available/000-default.conf
              environment:
                POSTGRES_HOST: db
                POSTGRES_DB: "{{ db_name }}"
                POSTGRES_USER: "{{ db_user }}"
                POSTGRES_PASSWORD: "{{ db_password }}"
                REDIS_HOST: redis
                NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
                NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
                TRUSTED_PROXIES: "{{ trusted_proxy }}"
                OVERWRITEPROTOCOL: https
                APACHE_SERVER_NAME: "{{ domain_name }}"
                NEXTCLOUD_TRUSTED_DOMAINS: |
                  {{ domain_name }}
                  {{ server_ip }}
              networks:
                - proxy_network
              dns:
                - 8.8.8.8
                - 1.1.1.1
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.cloud.rule=Host(`cloud.fixsys.org`)"
                - "traefik.http.routers.cloud.entrypoints=websecure"
                - "traefik.http.routers.cloud.tls.certresolver=letsencrypt"

            db:
              image: postgres:16
              container_name: cloud-db
              restart: always
              volumes:
                - /home/sasho/cloud/db:/var/lib/postgresql/data
              environment:
                POSTGRES_DB: nextcloud
                POSTGRES_USER: nextcloud
                POSTGRES_PASSWORD: 09876#Pmf
              networks:
                - proxy_network

            redis:
              image: redis:alpine
              container_name: cloud-redis
              restart: always
              networks:
                - proxy_network

            cron:
              image: nextcloud:latest
              container_name: cloud-cron
              restart: always
              volumes:
                - /home/sasho/cloud/data:/var/www/html/data
                - /home/sasho/cloud/config:/var/www/html/config
                - /home/sasho/cloud/custom_apps:/var/www/html/custom_apps
                - /home/sasho/cloud/themes:/var/www/html/themes
                - /home/sasho/cloud/logs:/var/www/html/data/logs
              entrypoint: /cron.sh
              depends_on:
                - db
                - redis
              networks:
                - proxy_network
              dns:
                - 8.8.8.8
                - 1.1.1.1

          networks:
            proxy_network:
              driver: bridge